print('What happens if you cross a neovik with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call a \'black hole\'?')
input()
print('Caries!')
print()
print('Knock Knock.')
input()
print("Who's there?")
input()
print('Impolite cow.')
input()
print('Impolite cow?', end='')
print('-Muu!')
